job_public_default:
    path: /
    defaults: { _controller: JobBundle:Front/Front:index}
job_public_search:
    path: /job-listing
    defaults: { _controller: JobBundle:Front/Front:search}

job_public_job_detail:
    path: /job-detail/{slug}
    defaults: { _controller: JobBundle:Front/Front:jobDetail}

job_public_load_more_job:
    path: /load-more-job
    defaults: { _controller: JobBundle:Front/FrontApi:loadMoreJob}


job_public_company_info:
    path: /company/{slug}
    defaults: { _controller: JobBundle:Front/Front:company}

