<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use DoctrineExtensions\Query\Mysql\Acos;
use DoctrineExtensions\Query\Mysql\Cos;
use DoctrineExtensions\Query\Mysql\Sin;
use DoctrineExtensions\Query\Mysql\Radians;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    /**
     *  booking of user
     * @param $user
     * @param $query
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findMyBooking($user,$query)
    {
        $expr = new Expr();
        $qb = $this->createQueryBuilder('booking')
            ->where($expr->eq('booking.user', ':user'))
            ->setParameter('user', $user);
        return $qb;

    }
    /**
     *  booking of host
     * @param $user
     * @param $query
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findHostBooking($user,$query)
    {
        $expr = new Expr();
        $qb = $this->createQueryBuilder('booking')
            ->join('booking.space','space')
            ->where($expr->eq('space.user', ':user'))
            ->setParameter('user', $user);
        return $qb;

    }
    public function getRatingSpace($space){
        return $this->_em->createQuery('select AVG((b.ratingLocation + b.ratingCommunication)/2) from AppBundle\Entity\Booking\Booking b where b.space =:space and b.ratingLocation > 0')
                    ->setParameter('space',$space)
                    ->getSingleScalarResult();
    }
    public function getLocationRatingSpace($space){
        return $this->_em->createQuery('select AVG(b.ratingLocation) from AppBundle\Entity\Booking\Booking b where b.space =:space and b.ratingLocation > 0')
                    ->setParameter('space',$space)
                    ->getSingleScalarResult();
    }
    public function getCommunicationRatingSpace($space){
        return $this->_em->createQuery('select AVG(b.ratingCommunication) from AppBundle\Entity\Booking\Booking b where b.space =:space and b.ratingLocation > 0')
                    ->setParameter('space',$space)
                    ->getSingleScalarResult();
    }
    public function getTotalReviewSpace($space){
        return $this->_em->createQuery('select COUNT(b.id) from AppBundle\Entity\Booking\Booking b where b.space =:space and b.ratingLocation > 0')
                    ->setParameter('space',$space)
                    ->getSingleScalarResult();
    }
    public function getTotalEarningSpace($space){
        return $this->_em->createQuery('select SUM (b.totalPrice) from AppBundle\Entity\Booking\Booking b where b.space =:space')
                    ->setParameter('space',$space)
                    ->getSingleScalarResult();
    }
  }
