<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use DoctrineExtensions\Query\Mysql\Acos;
use DoctrineExtensions\Query\Mysql\Cos;
use DoctrineExtensions\Query\Mysql\Sin;
use DoctrineExtensions\Query\Mysql\Radians;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

    public function findMyInbox($user)
    {
        $expr = new Expr();
        $qb = $this->createQueryBuilder('message')
            ->where($expr->eq('message.messageTo', ':user'))
            ->andWhere($expr->isNull('message.parent'))
            ->orderBy('message.createdAt','DESC')
            ->setParameter('user', $user);
        return $qb;
    }
    public function findMyOneInbox($user,$userFrom)
    {
        $expr = new Expr();
        $qb = $this->createQueryBuilder('message')
            ->where($expr->eq('message.messageTo', ':user'))
            ->andWhere('message.parent iS NULL')
            ->andWhere($expr->eq('message.messageFrom', ':userFrom'))
            ->orderBy('message.createdAt','DESC')
            ->setParameter('userFrom', $userFrom)
            ->setParameter('user', $user);
        return $qb->getQuery()->getSingleResult();
    }

}
