<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use DoctrineExtensions\Query\Mysql\Acos;
use DoctrineExtensions\Query\Mysql\Cos;
use DoctrineExtensions\Query\Mysql\Sin;
use DoctrineExtensions\Query\Mysql\Radians;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

    public function findMyInbox($user)
    {
        $expr = new Expr();
        $qb = $this->createQueryBuilder('message')
            ->where($expr->orX($expr->eq('message.messageTo', ':user'),$expr->eq('message.messageFrom', ':user')))
            ->andWhere($expr->isNull('message.parent'))
            ->orderBy('message.createdAt','DESC')
            ->setParameter('user', $user);
        return $qb;
    }

}
