<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpaceRepository extends EntityRepository
{
    public function findMySpaces($user){
        $expr= new Expr();
        $qb = $this->createQueryBuilder('space')
                ->where($expr->eq('space.user',':user'))
                ->setParameter('user',$user);
        return $qb;
        
    }
    public function searchSpaces(){
        $expr= new Expr();
        $qb = $this->createQueryBuilder('space');
        return $qb;

    }
}
