<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use DoctrineExtensions\Query\Mysql\Acos;
use DoctrineExtensions\Query\Mysql\Cos;
use DoctrineExtensions\Query\Mysql\Sin;
use DoctrineExtensions\Query\Mysql\Radians;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWishlistRepository extends EntityRepository
{

    public function findWishlist($user)
    {
        $expr = new Expr();
        $qb = $this->createQueryBuilder('wishlist')
            ->where($expr->eq('wishlist.user', ':user'))
            ->orderBy('wishlist.createdAt','DESC')
            ->setParameter('user', $user);
        return $qb;
    }
    public function findOneWishlist($user,$space)
    {
        $expr = new Expr();
        $qb = $this->createQueryBuilder('wishlist')
            ->where($expr->eq('wishlist.user', ':user'))
            ->andWhere($expr->eq('wishlist.space', ':space'))
            ->orderBy('wishlist.createdAt','DESC')
            ->setParameter('space', $space)
            ->setParameter('user', $user);
        return $qb->getQuery()->getOneOrNullResult();
    }

}
