app_front_search_spaces:
    path: /search-spaces
    defaults: { _controller: AppBundle:Front/Mgmt/PublicRetrieval:searchSpaces}
app_front_get_near_by_listing:
    path: /get-near-by-listing
    defaults: { _controller: AppBundle:Front/Api/PublicApi:getNearByListing}
