
app_user_default:
    path: /dashboard
    defaults: { _controller: AppBundle:User/Default:index}

app_user_space:
    resource: "@AppBundle/Resources/config/routing/user/space/routing.yml"
    prefix:   /space

