app_user_user_control_profile:
    path: /profile
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:profile}

app_user_user_control_setting:
    path: /setting
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:setting}

app_user_user_control_list_booking:
    path: /list-booking
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlRetrieval:listBooking}

app_user_user_control_review_space:
    path: /review-space/{booking}
    defaults: { _controller: AppBundle:User/UserControl/Mgmt/UserControlManipulation:reviewSpace}