app_user_host_control_list_booking:
    path: /list-booking
    defaults: { _controller: AppBundle:User/HostControl/Mgmt/HostControlRetrieval:listBooking}


app_user_host_control_dashboard:
    path: /dashboard
    defaults: { _controller: AppBundle:User/HostControl/Mgmt/HostControlManipulation:dashboard}

