services:
    admin.category:
            class: AppBundle\Admin\CategoryAdmin
            arguments: [~, AppBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Category }

    admin.blog_post:
            class: AppBundle\Admin\BlogPostAdmin
            arguments: [~, AppBundle\Entity\BlogPost, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Blog post }
    admin.space:
            class: AppBundle\Admin\SpaceAdmin
            arguments: [~, AppBundle\Entity\Space\Space, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Spaces }
