app_default:
    path: /
    defaults: { _controller: AppBundle:Default:index}

app_search_space:
    path: /search-spaces
    defaults: { _controller: AppBundle:Default:searchSpaces}

app_user:
    resource: "@AppBundle/Resources/config/routing/user/routing.yml"
    prefix:   /user

